### ISSUE TITLE
A strange log appears when using the MCMC optimization.yaml command

### ISSUE THREAD

**Issue by duxiaoxian** [PhasesResearchLab/ESPEI#108]
When using the command that will perform a MCMC optimization to create a cu-mg_mcmc.tdb,  strange logs appeared.  After completion, files such as trace can also be generated. Is this normal? 

distributed.process - WARNING - reaping stray process <Process(Dask Worker process (from Nanny), started daemon)>
distributed.process - WARNING - reaping stray process <Process(Dask Worker process (from Nanny), started daemon)>
distributed.process - WARNING - reaping stray process <Process(Dask Worker process (from Nanny), started daemon)>
distributed.nanny - WARNING - Worker process 1032 was killed by signal 15
distributed.nanny - WARNING - Worker process 10056 was killed by signal 15
distributed.nanny - WARNING - Worker process 6956 was killed by signal 15
[log.txt](https://github.com/PhasesResearchLab/ESPEI/files/3604410/log.txt)
[version-list.txt](https://github.com/PhasesResearchLab/ESPEI/files/3604411/version-list.txt)
[AG_CU_20190910.zip](https://github.com/PhasesResearchLab/ESPEI/files/3604414/AG_CU_20190910.zip)

**Comment by bocklund** [comment]
Hm, `signal 15` is [SIGTERM](https://people.cs.pitt.edu/~alanjawi/cs449/code/shell/UnixSignals.htm). You might be getting that if you're running out of memory or if your job is otherwise killed. 

You said that it completes, do you see the message at the end of the run or during? Does your calculation proceed after you get the message about your workers being killed?  I looked at your log, but it's not very clear what's happening. You can try to [increase the verbosity](http://espei.org/en/latest/writing_input.html#verbosity) from 0 to 1 (or 2, but that might be too much info).

**Comment by duxiaoxian** [comment]
Fortunately, I wrote verbosity = 1 and found that the log was normal and there was no termination problem.  Thank you for your help. This problem can be closed.
