### ISSUE TITLE
ERROR occurred using the new development version

### ISSUE THREAD

**Issue by duxiaoxian** [PhasesResearchLab/ESPEI#173]
Dear Administrator, 
There were some tests that failed when I try to run pytest after install the new development version(2021/4/21, Beijing time). 
Meanwhile, there is some error occurred when I run some example cases that successfully run using other versions before.
[errorlog.txt](https://github.com/PhasesResearchLab/ESPEI/files/6348496/errorlog.txt)
[pytestfail.txt](https://github.com/PhasesResearchLab/ESPEI/files/6348497/pytestfail.txt)
[condalist.txt](https://github.com/PhasesResearchLab/ESPEI/files/6348508/condalist.txt)

**Comment by bocklund** [comment]
The first file is saying that you have a version incompatibility in the symengine package for pycalphad. It looks like you have a development version of pycalphad installed. You may have wound up with incompatible versions depending on your environment and the steps you followed. Downgrading to symengine 0.6.1 from 0.7 should fix it. 

The tests are showing `289 passed, 4 skipped, 3 xfailed`, which is successful (`xfailed` means expected to fail, which is okay intended).

**Comment by duxiaoxian** [comment]
I used the development version of ESPEI 0.7.9+3.gd4625e7 and pycalphad 0.8.4 and it worked normally. The latest update mentions the modification of ZPF error, so I want to try the new version

**Comment by bocklund** [comment]
The tests are passing, so everything is good on ESPEI’s side. 

The version of pycalphad you have is compatible with both versions of SymEngine in practice, but the version of pycalphad that pip is seeing has the version pinned to 0.6.1, while you have 0.7 installed. `pip` is giving you the error in the first case because of this. `pip` only does the check on versions when you run ESPEI on the command line using the command script. 

Downgrading your version of symengine and python-symengine to the ones that are pinned by the version of pycalphad that you have installed should fix the error you get when trying to run ESPEI.

**Comment by duxiaoxian** [comment]
I'm sorry that my server broke down recently, so I can't try again.
Actually, the pycalphad I use is the development version obtained through your documentation step "instructions to install the development version of pycalphad", and pip is used to install the downloaded version of pycalphad.
Do you mean that I need to reinstall pycalhad not the development version but the version greater than 0.8?

**Comment by bocklund** [comment]
> Do you mean that I need to reinstall pycalhad not the development version but the version greater than 0.8?

Both the release version of pycalphad (currently 0.8.4) and the development version are should be compatible with the development version of ESPEI. You can use either one. 

The errror you saw is:

```
(espei2021) [msezbb-c@cas641 log-1000-zpf20-20210406]$ espei --input espei-in.yaml 
Traceback (most recent call last):
  File "/lustre/home/acct-msezbb/msezbb-c/.conda/envs/espei2021/lib/python3.9/site-packages/pkg_resources/__init__.py", line 582, in _build_master
    ws.require(__requires__)
  File "/lustre/home/acct-msezbb/msezbb-c/.conda/envs/espei2021/lib/python3.9/site-packages/pkg_resources/__init__.py", line 899, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/lustre/home/acct-msezbb/msezbb-c/.conda/envs/espei2021/lib/python3.9/site-packages/pkg_resources/__init__.py", line 790, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (symengine 0.7.0 (/lustre/home/acct-msezbb/msezbb-c/.conda/envs/espei2021/lib/python3.9/site-packages), Requirement.parse('symengine==0.6.1'), {'pycalphad'})
```

The symptom here is that you have symengine 0.7.0 installed, but the version of pycalphad that you have installed wants to be using symengine 0.6.1. I can't see which version of pycalphad and ESPEI you have installed from `conda list` because they look like this:

```
espei=0+unknown=dev_0
pycalphad=0+unknown=dev_0
```

Did you download the zipped files from GitHub or use `git clone` as in the instructions? It's important to pull the whole repository down, since the version number requires a tagged versions in the git history to be detected correctly.

**Comment by duxiaoxian** [comment]
Yes, I downloaded the newest zip file from https://github.com/pycalphad/pycalphad. The installation process follows the steps https://pycalphad.org/docs/latest/INSTALLING.html#development-versions-advanced-users.  I don’t know why the latest zip does not show the version number. I have installed development version pycalphad 0.8.4  successfully before and it can display the version number but now it can't.

**Comment by bocklund** [comment]
The version doesn’t show because you need to `git clone` the repository instead of downloading the zip.

Is there a certain feature you need in the development version? I’m hoping that we can get pycalphad 0.8.5 out sometime this week, so maybe the release versions will work for you?

**Comment by duxiaoxian** [comment]
I’m not in a hurry but just want to try it. Our server can’t git clone because of network problems now, so I can only wait for you to release the new version. Thank you very much for your kind help.

**Comment by bocklund** [comment]
It should be able to pick up the version correctly if you `git clone` locally and then push that archive to your server, if that's possible. Basically, you need the `pycalphad/.git` and `espei/.git` directories that contain the git history for each package

**Comment by duxiaoxian** [comment]
Thanks for informing. I will ask the network center to check why it can't git now and try again. /(ㄒoㄒ)/~~

**Comment by bocklund** [comment]
+1

I'll close this for now. If you are still having trouble with installation issues when you try again, you may re-open this issue or (preferably) start a new [Discussion on GitHub](https://github.com/PhasesResearchLab/ESPEI/discussions/categories/q-a)
