### ISSUE TITLE
Some doubt about parameter selection?

### ISSUE THREAD

**Issue by superjery** [PhasesResearchLab/ESPEI#88]
I see ESPEI using AICc to prevent over estimation of parameters.
But F-test was mentioned in Doctor thesis "SOFTWARE ARCHITECTURE FOR CALPHAD MODELING OF PHASE STABILITY AND TRANSFORMATIONS IN ALLOY ADDITIVE MANUFACTURING PROCESSES".

In the thesis AICc is used to fit sigle-phase parameters and F-test is used to fit multi-phases parameters. It looks like ESPEI only using AICc and not using F-test.

question:
(1) Does AICc is suitable for multi-phases?
(2) Why not taking F-test into consideration?

**Comment by bocklund** [comment]
1. It is theoretically possible to use the AICc or other criteria to compare models. ESPEI does not do this because fitting multiphase data is relatively expensive in terms of computation time, so comparing candidate models fit to multiphase data is not practical.
2. The main assumption is that AICc can give the correct model features, but not the most optimal values in terms of all the thermochemistry and phase diagram data. MCMC optimizes the AICc-selected parameters to all the available data. The F-test is unnecessary in this concept and was removed quite some time ago.


In the future, I would encourage you to only open issues for bugs or actionable software issues. Questions, discussion, and support topics should occur on [gitter](
https://gitter.im/PhasesResearchLab/ESPEI).
